import json, os

ROOT = os.path.join(os.path.dirname(__file__), '..')
IPY = {'cells': [], 'metadata': {'kernelspec': {'display_name': 'Python 3 (fund)', 'language': 'python', 'name': 'python3'}, 'language_info': {'name': 'python', 'version': '3.12'}}, 'nbformat': 4, 'nbformat_minor': 5}

def md(s):
    IPY['cells'].append({'cell_type': 'markdown', 'metadata': {}, 'source': s.splitlines(True)})

def code(s):
    IPY['cells'].append({'cell_type': 'code', 'metadata': {}, 'execution_count': None, 'outputs': [], 'source': s.splitlines(True)})

def build():
    md('''# 巴菲特质量代理 —— A 股年度回测\n\n本 notebook 不把巴菲特的投资过程伪装成一个简单公式。由于当前离线数据中带公告日期的现金流量表只有 8 家，批量抓取 EBIT、净债务、资本投入和 owner earnings 会显著增加数据获取成本，且难以保证历史点时一致。本版使用可审计的低成本代理：5 年正盈利与增长、低盈利波动、ROE、低杠杆、流动性、合理估值、市值和行业安全门槛。\n\n这检验的是"可持续质量 + 合理价格 + 低换手"，不是原始 EBIT/EV 神奇公式，也不是巴菲特完整的护城河、管理层和资本配置判断。\n\n## 口径\n\n- 信号在调仓日收盘形成，下一交易日成交；财报公告日期严格不晚于信号日。\n- 每年 7 月调仓一次，20 只等权，单行业最多 3 只；回测持有到 `END`。\n- 使用原始价格，分红按除权日显式入账，并按持有期扣除个人股息税，不使用前复权净值。\n- 未知行业不绕过行业过滤；当前名称只能排除当前标记 ST，历史 ST 状态仍需后续接入点时证券状态数据。\n''')
    code('''import os, sys, warnings\nimport pandas as pd, numpy as np\nwarnings.filterwarnings('ignore')\n_ROOT = os.getcwd()\nfor _ in range(4):\n    if os.path.exists(os.path.join(_ROOT, 'scripts', 'graham_dodd_lib.py')): break\n    _ROOT = os.path.dirname(_ROOT)\nos.chdir(_ROOT); sys.path.insert(0, os.path.join(_ROOT, 'scripts'))\nfrom graham_dodd_lib import (load_universe, load_balance, load_profit, load_market,\n    load_index, perf_metrics, END)\nfrom buffett_quality_lib import (annual_signal_dates, rank_candidates, build_ranking_map,\n    audit_borderline, QualityBacktest, FUNNEL_BQ, N_HOLDINGS, EXCLUDED_INDUSTRIES,\n    MIN_SIZE_QUANTILE)\npd.set_option('display.width', 220); pd.set_option('display.max_columns', 40)\nINITIAL_CAPITAL = 1_000_000.0\nprint('质量代理参:', f'N_HOLDINGS={N_HOLDINGS}', f'MIN_SIZE=P{MIN_SIZE_QUANTILE:.0%}',\n      f'行业排除{len(EXCLUDED_INDUSTRIES)}类', '单行业最多3只')\n''')
    md('## 1. 数据现状核查')
    code('''uni = load_universe()\nhas_bal = sum(1 for c in uni['code'] if load_balance(c) is not None)\nhas_pro = sum(1 for c in uni['code'] if load_profit(c) is not None)\nhas_mkt = sum(1 for c in uni['code'] if load_market(c, qfq=False) is not None)\nsignals = annual_signal_dates()\nprint(f'资产池(全部A股): {len(uni)} 只  (当前 {int((uni.kind=="current").sum())} / 退市 {int((uni.kind=="delisted").sum())})')\nprint(f'资产负债表覆盖: {has_bal} ({has_bal/len(uni):.1%})  利润表覆盖: {has_pro} ({has_pro/len(uni):.1%})')\nprint(f'行情覆盖(不复权): {has_mkt}  行业已知: {(uni.industry.fillna("") != "").sum()} ({((uni.industry.fillna("")) != "").mean():.1%})')\nprint(f'信号日(每年7月): {[d.date().isoformat() for d in signals]}')\nprint(f'可用现金流量表: {sum(os.path.exists(f"data/financial/{c}_cashflow.csv") for c in uni.code)} 家')\nprint('质量门槛: 近5年EPS均为正、CAGR>=5%、下滑<=1年、ROE>=15%、PE<=30、负债/权益<1、流动比率>=1')\n''')
    md('## 2. 首期质量池与点检对比')
    code('''D = signals[0]; df = rank_candidates(D)\nf = FUNNEL_BQ[D]\nprint(f'信号日 {D.date()}  市值门槛(质量候选市值P{MIN_SIZE_QUANTILE:.0%})={f["floor"]/1e8:.0f}亿')\nprint(f'  门槛漏斗: 可交易{f["tradable"]} → 排除ST{f["st"]} → '\n      f'行业排除{f["industry"]} → 质量未过{f["quality"]} → '\n      f'市值未过{f["size"]} → 终选{len(df)}只')\nprint(f'通过质量池 {len(df)} 只, Top{N_HOLDINGS} 名单与逐项指标:')\nprint(df.head(N_HOLDINGS).round(4).to_string(index=False))\n''')
    md('''### 接近候选明细\n\n以下为未入质量池但距门槛最近的标的 (按未达标项数从少到多), 逐项列出未达标原因。\n''')
    code('''for r in audit_borderline(D, top=12):\n    print(f"{r['code']} {r['name']:8s} {r['industry']:6s} 价格{r['price']:8.2f}  未达标{r['n_fails']}项  [{', '.join(r['fails'])}]")\n''')
    md('## 3. 年度回测执行')
    code('''ranking_map = build_ranking_map(signals, n=N_HOLDINGS)\nbt = QualityBacktest(initial_capital=INITIAL_CAPITAL, n=N_HOLDINGS)\nnav, trades, dates = bt.run(signals, ranking_map, end=pd.Timestamp(END))\nprint(f'回测完成: {len(trades)} 笔交易, 净值点数 {len(nav)}')\nprint(f'期末净值: {nav.iloc[-1]:,.2f} 元  ({(nav.iloc[-1]/INITIAL_CAPITAL-1):+.2%})')\n''')
    md('## 4. 每个阶段的调仓动作说明\n\n下表按信号日列出: 质量池通过数、买入动作、股数与成交价、当季期末净值 (含成本)。')
    code('''TRADE_COLS = ['date','code','name','action','shares','price','proceeds','fee','reason']\ntrades_df = pd.DataFrame(trades, columns=TRADE_COLS)\ndef period_table(D, bt):\n    t = trades_df[trades_df['date'] == D]\n    if t.empty:\n        return pd.DataFrame()\n    out = []\n    for _, x in t.iterrows():\n        out.append({'成交日': D.date(), '代码': x.code, '名称': x['name'],\n                    '动作': ('买入' if x.action=='buy' else '卖出'),\n                    '股数': int(x.shares) if x.shares and x.shares>0 else '—',\n                    '成交价': f"{x.price:.2f}" if np.isfinite(x.price) else '—',\n                    '金额': f"{x.proceeds:,.0f}",\n                    '费用': f"{x.fee:.2f}",\n                    '理由': x.reason})\n    return pd.DataFrame(out)\n\nlines = []\nfor D in signals:\n    f = FUNNEL_BQ.get(D, {})\n    p = next((p for p in bt.periods if p.get('signal_date') == D), None)\n    execDay = p['date'] if p else None\n    lines.append(f"### 信号日 {D.date()}" + (f" -> 成交 {execDay.date()}" if execDay is not None else ''))\n    lines.append(f"- 通过质量池(市值门槛后): **{f.get('final_pool', 0)}** 只")\n    names = '、'.join(f"{r['code']} {r['name']}" for _, r in ranking_map.get(D, pd.DataFrame()).iterrows()) or '无(全持币)'\n    lines.append(f"- Top{N_HOLDINGS}: {names}")\n    df = period_table(execDay, bt) if execDay is not None else pd.DataFrame()\n    if df.empty:\n        lines.append('- 本期无买卖调仓。')\n    else:\n        lines.append('')\n        lines.append(df.to_string(index=False))\n    navD = bt.nav_curve.get(execDay, np.nan) if execDay is not None else np.nan\n    lines.append(f"- 当季期末净值: {navD:,.2f} 元 `(`现金或持仓市值合计`)`" if np.isfinite(navD) else '- 当季期末净值: (无)')\n    lines.append('')\nprint('\\n'.join(lines))\n''')
    md('## 5. 防御性校验: 门槛漏斗 · 行业分布\n\n**(a) 门槛漏斗** 与 **(b) 持仓行业分布** 逐期核查, 避免单一行业/主题堆积。')
    code('''# (a) 门槛漏斗: 每个信号日一次全市场扫描的统计数据\nfunnel = pd.DataFrame([{'日期': d.date(), '可交易': FUNNEL_BQ.get(d, {}).get('tradable', 0),\n                        '排除ST': FUNNEL_BQ.get(d, {}).get('st', 0),\n                        '行业排除': FUNNEL_BQ.get(d, {}).get('industry', 0),\n                        '质量未过': FUNNEL_BQ.get(d, {}).get('quality', 0),\n                        '市值未过': FUNNEL_BQ.get(d, {}).get('size', 0),\n                        '终选池': FUNNEL_BQ.get(d, {}).get('final_pool', 0)} for d in signals])\nprint('门槛漏斗 (各信号日通过数):')\nprint(funnel.to_string(index=False))\n''')
    code('''# (b) 持仓行业分布 (每信号日, 按投资市值的前 5 行业)\nfor p in bt.periods:\n    mark = bt.nav_curve.get(p['date'], np.nan)\n    inds = sorted((k for k in p['industry'].items() if k[0]), key=lambda kv: -kv[1])[:5]\n    share = f"{sum(v for _, v in inds) / mark:.0%}" if np.isfinite(mark) and mark > 0 else '—'\n    top = '、'.join(f"{k}({v / mark:.0%})" for k, v in inds) if np.isfinite(mark) and mark > 0 else '·'\n    print(f"{p['date'].date()}: 前5行业占净值 {share}  -> {top}")\n''')
    md('## 6. 净值曲线与基准对比')
    code('''base = nav / INITIAL_CAPITAL\nbench = {}\nfor label, code_ in [('沪深300','000300'), ('中证800','000906')]:\n    x = load_index(code_).loc[base.index[0]:base.index[-1], 'close']; bench[label] = x / x.iloc[0]\ncomp = pd.DataFrame({'巴菲特质量代理(含成本)': base, **bench}).ffill().dropna(subset=['巴菲特质量代理(含成本)'])\ncomp.tail(8).round(4)\n''')
    code('''import matplotlib\nmatplotlib.use('Agg')\nimport matplotlib.pyplot as plt\nfrom IPython.display import Image, display\nplt.rcParams['font.sans-serif'] = ['Heiti TC', 'STHeiti', 'Songti SC']\nplt.rcParams['axes.unicode_minus'] = False\nos.makedirs('reports/generated/magic_formula', exist_ok=True)\nfig, ax = plt.subplots(figsize=(12, 5.5))\nfor c in comp.columns:\n    ax.plot(comp[c], label=c, linewidth=1.6)\nax.set_title('巴菲特质量代理 · A股 年度调仓 vs 基准')\nax.set_ylabel('净值 (起点=1)'); ax.legend(); ax.grid(alpha=0.3)\nplt.tight_layout()\nimg = 'reports/generated/magic_formula/nav_compare.png'\nfig.savefig(img, dpi=110)\nplt.close(fig)\ncomp.to_csv('reports/generated/magic_formula/nav_compare.csv')\ndisplay(Image(filename=img))\nprint('净值对比图: reports/generated/magic_formula/nav_compare.png')\n''')
    md('## 7. 绩效口径')
    code('''m = perf_metrics(nav)\nlabels = {'total_return':'累计收益','annual_return':'年化收益','annual_vol':'年化波动',\n          'sharpe':'夏普','max_drawdown':'最大回撤','win_rate':'日胜率'}\nprint(f"{'期末权益':<12} {nav.iloc[-1]:,.0f} 元")\norder = ['total_return','annual_return','annual_vol','sharpe','max_drawdown','win_rate']\nfor k in order:\n    v = m.get(k)\n    if k in ('total_return','annual_return','annual_vol','max_drawdown'):\n        print(f"{labels[k]:<12} {v:+.2%}")\n    else:\n        print(f"{labels[k]:<12} {v:+.4f}")\nprint(f"{'调仓次数':<12} {len(dates)}")\nprint(f"{'交易笔数':<12} {len(trades_df)}  (买 {len(trades_df[trades_df.action=='buy'])}, 卖 {len(trades_df[trades_df.action=='sell'])})")\nprint(f"{'持仓期占比':<12} {(bt.holdings_curve>0).mean():.1%}")\nbuys = trades_df[trades_df['action']=='buy']['proceeds'].sum()\nprint(f"{'累计买入金额':<12} {buys:,.0f} 元")\n''')
    md('## 8. 结论与局限\n\n当前版本优先保证点时、低换手和可复现。真正接近巴菲特还需要逐期现金流量表、资本开支、净现金/有息负债、扣非利润、护城河和管理层/治理变量。建议先对少量候选公司补抓这些字段，再做增量实验，不要把全市场缺失数据默认为零。')
    with open(os.path.join(ROOT, 'notebooks', 'magic_formula_a_share.ipynb'), 'w') as f:
        json.dump(IPY, f, ensure_ascii=False, indent=1)

if __name__ == '__main__': build()